In [1]:
import tensorflow as tf
import numpy as np
# calculate algebraic summation in the Gram matrix formuls
from tensorflow import linalg
# add dimension to tensor
from tensorflow import expand_dims
# shape of tensor
from tensorflow import shape
from tensorflow import cast

2023-05-14 14:59:22.013742: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


GRAM MATRIX

In [23]:
# test tensor
a = tf.constant([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

def gram_matrix(tensor):
    '''determines the strength of the correlation between two style features'''
    temp = tensor
    print("calculating gram matrix: ")
    
    # get shape of input tensor
    shape = tf.shape(temp)
    print("original shape: ")
    print(shape)

    # flatten tensor into 2D
    t_reshape = tf.reshape(temp, [shape[2], shape[1] * shape[0]])
    print("flattened tensor: ")
    print(tf.shape(t_reshape))

    # multiply matrix by its transpose
    result = tf.matmul(t_reshape, t_reshape, transpose_b=True)
    gram_matrix = tf.expand_dims(result, axis=0)
    print("gram matrix: ")
    return gram_matrix

gram_matrix(a)



calculating gram matrix: 
original shape: 
tf.Tensor([3 3 3], shape=(3,), dtype=int32)
flattened tensor: 
tf.Tensor([3 9], shape=(2,), dtype=int32)
gram matrix: 


<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[ 285,  735, 1185],
        [ 735, 2085, 3435],
        [1185, 3435, 5685]]], dtype=int32)>